### ISSUE TITLE
How should the LayerTimelineController notify the StudioCtrl? 

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/AndroidIconAnimator#76]
Hey Roman, I'm going to just file this as a question and maybe you can give me a hint when you get a chance. :D

I've been trying to figure out how to add an "Import" menu to allow SVGs to be imported via a file picker (as opposed to drag and drop), and I've basically got everything working *except* the part where the svg text content is somehow passed from the `LayerTimelineController` to the `StudioCtrl`.

StudioCtrl has an `onDropFile(fileInfo)` method that will trigger exactly the control flow I want... but I guess this is the part of angular I don't really understand yet (i.e. how communication between different controllers work and stuff).

If you have any advice that'd be cool. :D

**Comment by romannurik** [comment]
In my CL f942bf24eab4d368c4ef950937f796a7a30ba48f, I moved a lot of the "add svg layers" logic out of `StudioCtrl` to `StudioStateService`. It's cleaner to rely on a global service to do some of this work rather than coupling `LayerTimelineController` to `StudioCtrl`.

In the future, if there's a compelling reason to couple them, you can try injecting `StudioCtrl` in the [child controller's constructor](https://github.com/romannurik/AndroidIconAnimator/blob/master/app/components/layertimeline/layertimeline.js#L38)
